### ISSUE TITLE
Error executing the dovecot::ohai_plugin recipe

### ISSUE THREAD

**Issue by MrSeccubus** [onddo/dovecot-cookbook#40]
### Cookbook Version
3.2.1

### Chef Client Version
18.2.7

### Platform Details
Ubuntu 22.04 LTS

### Scenario
Install Docevot

### Steps to Reproduce
Add `recipe[dovecot]` to runlist

### Expected Result
Dovecot gets installed

### Actual Result
```
Recipe: dovecot::ohai_plugin
  * ohai_plugin[dovecot] action create

    ================================================================================
    ESC[31mError executing action `create` on resource 'ohai_plugin[dovecot]'ESC[0m
    ================================================================================

    NameError
    ---------
    undefined local variable or method `path' for #<#<Class:0x00007fa3cea3b410>:0x00007fa3ce398630 @new_resource=<ohai_plugin[dovecot] @name: "dovecot" @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :create, :delete] @action: [:create] @updated: false @updated_by_last_action: false @source_line: "/var/chef/cache/cookbooks/dovecot/recipes/ohai_plugin.rb:34:in `from_file'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @declared_type: :ohai_plugin @cookbook_name: "dovecot" @recipe_name: "ohai_plugin" @source_file: "ohai7_plugins/dovecot.rb.erb" @resource: :template @variables: {:enable_build_options=>true}>, @action=:create, @current_resource=nil, @after_resource=nil, @run_context=#<Chef::RunContext:0x00007fa3d0073660 @events=#<Chef::EventDispatch::Dispatcher:0x00007fa3cf9321f8 @subscribers=[#<Chef::Formatters::Doc:0x00007fa3cf92c258 @output=#<Chef::Formatters::IndentableOutputStream:0x00007fa3cf933c60 @err=#<IO:<STDERR>>, @out=#<IO:<STDOUT>>, @indent=4, @line_started=true, @semaphore=#<Thread::Mutex:0x00007fa3cf933670>, @pastel=#<Pastel styles=[]>, @current_stream=<ohai_plugin[dovecot] @name: "dovecot" @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :create, :delete] @action: [:create] @updated: false @updated_by_last_action: false @source_line: "/var/chef/cache/cookbooks/dovecot/recipes/ohai_plugin.rb:34:in `from_file'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @declared_type: :ohai_plugin @cookbook_name: "dovecot" @recipe_name: "ohai_plugin" @source_file: "ohai7_plugins/dovecot.rb.erb" @resource: :template @variables: {:enable_build_options=>true}>>, @updated_resources=0, @up_to_date_resources=1, @start_time=2023-07-26 10:12:58.70099342 +0200, @end_time=2023-07-26 10:12:58.70099342 +0200, @skipped_resources=0, @progress={}, @current_recipe="dovecot::ohai_plugin">, #<Chef::ActionCollection:0x00007fa3cf934f48 @action_records=[#<Chef::ActionCollection::ActionRecord:0x00007fa3cf8a2558 @new_resource=<chef_gem[acme-client] @package_name: "acme-client" @name: "acme-client" @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :install, :upgrade, :remove, :purge, :reconfig, :lock, :unlock] @action: [:nothing] @updated: false @updated_by_last_action: false @source_line: "/var/chef/cache/cookbooks/acme/recipes/default.rb:21:in `from_file'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0.154998827 @declared_type: :chef_gem @cookbook_name: "acme" @recipe_name: "default" @version: "2.0.13" @compile_time: true @gem_binary: "/opt/chef/embedded/bin/gem">, @action=:install, @nesting_level=0, @current_resource=<gem_package[acme-client] @package_name: "acme-client" @name: "acme-client" @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :install, :upgrade, :remove, :purge, :reconfig, :lock, :unlock] @action: [:install] @updated: false @updated_by_last_action: false @source_line: nil @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @version: "2.0.13">, @status=:up_to_date, @after_resource=<chef_gem[acme-client] @package_name: "acme-client" @name: "acme-client" @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :install, :upgrade, :remove, :purge, :reconfig, :lock, :unlock] @action: [:nothing] @updated: false @updated_by_last_action: false @source_line: "/var/chef/cache/cookbooks/acme/recipes/default.rb:21:in `from_file'" @guard_interpreter: nil @default_guard_interpreter: :default 

<snip>

```

**Comment by MrSeccubus** [comment]
This is likely directly related to #39
